### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by barchard** [PeachFlame/cPanel-fixperms#2]
hi, i'm receiving the following error when i run this script. seems like a path parsing issue?

```
chown: cannot access ‘On"}]}},"enable_sni_for_mail":"1","group":"xyz","owner":"root","usecanonicalname":"Off","customlog":[{"target":"/etc/apache2/logs/domlogs/xyz.xyzhosting.com","format":"combined"}],"documentroot":"/home/xyz/xyz-websites/xyzhosting","sslcertificatefile":"/var/cpanel/ssl/installed/certs/_wildcard__xyzhosting_com_cbc7b_7ab37_1533513599_4b02ce0d75f4eae7d6dab9986e65cd4e.crt","secruleengineoff":null,"ifmodulemodsuphpc":{"group":"xyz"},"options":"-ExecCGI’: No such file or directory
find: ‘On"}]}},"enable_sni_for_mail":"1","group":"xyz","owner":"root","usecanonicalname":"Off","customlog":[{"target":"/etc/apache2/logs/domlogs/xyz.xyzhosting.com","format":"combined"}],"documentroot":"/home/xyz/xyz-websites/xyzhosting","sslcertificatefile":"/var/cpanel/ssl/installed/certs/_wildcard__xyzhosting_com_cbc7b_7ab37_1533513599_4b02ce0d75f4eae7d6dab9986e65cd4e.crt","secruleengineoff":null,"ifmodulemodsuphpc":{"group":"xyz"},"options":"-ExecCGI’: No such file or directory
```

**Comment by boomshadow** [comment]
Those errors are probably being spit out from lines 115 & 116. I would guess something is different about your setup that's causing the Subdomain lookup in line 107 to receive unexpected information:

https://github.com/PeachFlame/cPanel-fixperms/blob/8c17a44b34084d31d00e15e04d4eba5edfe0b4a2/fixperms.sh#L107-L118

What happens when you run the following command? (Be sure to replace USERNAME with your actual username):

    `grep -i document /var/cpanel/userdata/USERNAME/* | awk '{print $2}' | grep home | grep -v public_html`

**Comment by boomshadow** [comment]
Actually, there was some cleanup that could be done on the command that looks for document root. I believe you were getting the SSL or Cache files for some reason. Let me know if this doesn't fix the problem for you.
